# Generated by Django 2.2 on 2020-06-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Professional', 'pro'), ('Free', 'free')], default='Free', max_length=30),
        ),
    ]
