# Generated by Django 2.2 on 2020-06-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200524_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
